routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});
Route::resource('position',PositionController::class);
Route::resource('employee',EmployeeController::class);
Route::get('/employee/switch/{is}', [EmployeeController::class, 'switch'])->name('switch');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $fillable = [
        'name', 'nip', 'position_id', 'department', 'birth_date', 'address', 'phone_number', 'religion', 'status','ktp'
    ];
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Position;
use Illuminate\Http\Request;
use App\Http\Requests\EmployeeRequest;
use App\Http\Requests\EmployeeEditRequest;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use RealRashid\SweetAlert\Facades\Alert;




class EmployeeController extends Controller
{

    public function index()
    {
        $employee = Employee::select('*', 'positions.name as position', 'employees.name as fullname', 'employees.id as ID_emp')
            ->join('positions', 'employees.position_id', '=', 'positions.id')
            ->get();
        if (request()->ajax()) {

            return datatables($employee)
                ->addIndexColumn()
                ->addColumn('status', function(Employee $employee){
                if ($employee->status == 1){
                    return '<span class="badge badge-pill badge-success">Aktif</span>';

                }
                else{
                    return '<span class="badge badge-pill badge-danger">Nonaktif</span>';
                }

                })
                ->addColumn('action', function(Employee $employee) {
                    if ($employee->status==1) {
                        $text="Nonaktifkan";
                    }else{
                        $text="Aktifkan";
                    }
                    return
                    '<div class="dropdown">
                    <button class="btn btn-info btn-sm dropdown-toggle" type="button" id="actionDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Opsi
                    </button>
                    <div class="dropdown-menu" aria-labelledby="actionDropdown">

                      <a class="dropdown-item" href="'.route('employee.show', $employee->ID_emp).'">Detail karyawan</a>
                      <a class="dropdown-item" href="'.route('employee.edit', $employee->ID_emp).'">Edit data karyawan</a>
                      <a class="dropdown-item" href="'.route('switch', $employee->ID_emp).'">'.$text.' karyawan</a>
                      <form action="'.route('employee.destroy', $employee->ID_emp).'" method="post" id="delete_from_'.$employee->ID_emp.'">
                      <input type="hidden" name="_method" value="DELETE">
                      <input type="hidden" name="_token" value="'.csrf_token().'">
                      <button type="submit class="delete_data" class="dropdown-item">Hapus data karyawan</button>

                       </form>
                    </div>
                  </div>
                  ';
                })
                ->rawColumns(['status', 'action'])
                ->toJson();
        }
        return view('employee.index');
    }


    public function create()
    {
        $data = [
            'position'=> Position::all(),
            'currentYear' => Carbon::now()->year,

        ];

        return view('employee.create', $data);
    }


    public function store(EmployeeRequest $request)
    {
        //validate data
        $validatedData = $request->validated();
       // Generate a unique, random name...
        $name=$request->file('ktp')->hashName();
        //upload image
        Storage::putFileAs(
            'public/ktp', $request->file('ktp'), $name
        );

        //store data
        $validatedData['ktp']=$name;
        Employee::create($validatedData);
        Alert::toast('Berhasil menambahkan karyawan', 'success')->autoClose(2000);

        return redirect()->route('employee.index');
    }


    public function show(Employee $employee)
    {
        $data['employee']=Employee::select('*', 'positions.name as position', 'employees.name as fullname', 'employees.id as ID_emp')
        ->join('positions', 'employees.position_id', '=', 'positions.id')
        ->find($employee->id);
        return view('employee.show',$data);
    }


    public function edit(Employee $employee)
    {
        $data = [
            'position'=> Position::all(),
            'currentYear' => Carbon::now()->year,
            'selectedDate'=>Carbon::createFromFormat('Y-m-d', $employee->birth_date)->format('d'),
            'selectedMonth'=>Carbon::createFromFormat('Y-m-d', $employee->birth_date)->format('m'),
            'selectedYear'=>Carbon::createFromFormat('Y-m-d', $employee->birth_date)->format('Y'),
            'employee'=>$employee
        ];
        return view('employee.edit', $data);

    }


    public function update(EmployeeEditRequest $request, Employee $employee)
    {
        $validatedData = $request->validated();
        // if File input has a value

        if ($request->hasFile('ktp')) {
            // Generate a unique, random name...
            $name=$request->file('ktp')->hashName();
            //upload image
            Storage::putFileAs(
                'public/ktp', $request->file('ktp'), $name
            );
            $validatedData['ktp']=$name;
            //delete old file
            $old_path='/ktp/'.$employee->ktp;
            if (Storage::disk('public')->exists($old_path)) {
                Storage::disk('public')->delete($old_path);
            } else {
                return redirect()->back()->withErrors(['error' => 'File not found']);
            }
        }
        Employee::where('id',$employee->id)
        ->update($validatedData);
        Alert::toast('Data '.$employee->name.' berhasil diubah', 'success')->autoClose(2000);

        return redirect()->route('employee.show',$employee->id);

    }

    public function switch($id)
    {
        $employee = Employee::find($id);
        $old_status = $employee->status;
        $alert="";
        $new_status=0;
        //switch status
        if ($old_status==1) {
            $new_status=0;
            $alert="dinonaktifkan";
        }elseif($old_status==0){
            $new_status=1;
            $alert="diaktifkan kembali";
        }
        //update
        $data['status']=$new_status;
        Employee::where('id',$id)
        ->update($data);
        Alert::toast($employee->name.' berhasil '.$alert.'', 'success')->autoClose(2000);
        return redirect()->route('employee.index');
    }
    public function destroy(Employee $employee)
    {
        $path='/ktp/'.$employee->ktp;
        if (Storage::disk('public')->exists($path)) {
            Storage::disk('public')->delete($path);
        } else {
            return redirect()->back()->withErrors(['error' => 'File not found']);
        }
        Employee::destroy($employee->id);
        Alert::toast('Data '.$employee->name.' berhasil dihapus', 'success')->autoClose(2000);
        return redirect()->route('employee.index');

    }
}

resources/views/employee/create.blade.php
@extends('layout.app')

@section('css')
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
@endsection
@section('breadcrumb')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Data Karyawan</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
            <li class="breadcrumb-item">
                <a href="{{ route('employee.index') }}">Karyawan</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Tambah Karyawan</li>
        </ol>
    </div>
@endsection
@section('content')
    <form action="{{ route('employee.store') }}" method="POST" class="row" id="employeeForm"
        enctype="multipart/form-data">
        @csrf
        <div class="col-md-6">
            <div class="card">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Identitas Karyawan</h6>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label class="label" for="name">Nama Lengkap</label>
                        <input type="text" class="form-control" name="name" placeholder="Masukkan nama lengkap"
                            value="{{ old('name') }}">
                        @if ($errors->has('name'))
                            <div class="error">{{ $errors->first('name') }}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="label d-block" for="birth_date">Tanggal Lahir</label>
                        <select class="custom-select w-auto date_of_birth" id="select_day" name="select_day">
                            <option value="">--</option>
                            @for ($i = 1; $i <= 31; $i++)
                                <option value="{{ $i }}" {{ old('select_day') == $i ? 'selected' : '' }}>
                                    {{ $i }} </option>
                            @endfor
                        </select>
                        <select id="select_month" class="custom-select w-auto date_of_birth" name="select_month">
                            <option value="">--</option>
                            <option value="01" {{ old('select_month') == '01' ? 'selected' : '' }}>Januari</option>
                            <option value="02" {{ old('select_month') == '02' ? 'selected' : '' }}>Februari</option>
                            <option value="03" {{ old('select_month') == '03' ? 'selected' : '' }}>Maret</option>
                            <option value="04" {{ old('select_month') == '04' ? 'selected' : '' }}>April</option>
                            <option value="05" {{ old('select_month') == '05' ? 'selected' : '' }}>Mei</option>
                            <option value="06" {{ old('select_month') == '06' ? 'selected' : '' }}>Juni</option>
                            <option value="07" {{ old('select_month') == '07' ? 'selected' : '' }}>Juli</option>
                            <option value="08" {{ old('select_month') == '08' ? 'selected' : '' }}>Agustus</option>
                            <option value="09" {{ old('select_month') == '09' ? 'selected' : '' }}>September</option>
                            <option value="10" {{ old('select_month') == '10' ? 'selected' : '' }}>Oktober</option>
                            <option value="11" {{ old('select_month') == '11' ? 'selected' : '' }}>November</option>
                            <option value="12" {{ old('select_month') == '12' ? 'selected' : '' }}>Desember</option>
                        </select>

                        <select id="select_year" class="custom-select w-auto date_of_birth" name="select_year">
                            <option value="">--</option>
                            @for ($i = $currentYear; $i > $currentYear - 100; $i--)
                                <option value="{{ $i }}" {{ old('select_year') == $i ? 'selected' : '' }}>
                                    {{ $i }} </option>
                            @endfor
                        </select>
                        <input type="hidden" name="birth_date" id="birth_date">
                        @if ($errors->has('birth_date'))
                            <div class="error">{{ $errors->first('birth_date') }}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="label" for="phone_number">Nomor Telepon</label>
                        <input type="tel" name="phone_number" class="form-control" placeholder="Masukkan nomor telepon"
                            value="{{ old('phone_number') }}">
                        @if ($errors->has('phone_number'))
                            <div class="error">{{ $errors->first('phone_number') }}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="label" for="address">Alamat</label>
                        <textarea name="address" class="form-control">{{ old('address') }}</textarea>
                        @if ($errors->has('address'))
                            <div class="error">{{ $errors->first('address') }}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="label" for="religion">Agama</label>

                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="religion" value="Islam" id="Islam"
                                {{ old('religion') == 'Islam' ? 'checked' : '' }}>
                            <label class="form-check-label" for="Islam">
                                Islam
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="religion" value="Kristen Protestan"
                                id="Kristen Protestan" {{ old('religion') == 'Kristen Protestan' ? 'checked' : '' }}>
                            <label class="form-check-label" for="Kristen Protestan">
                                Kristen Protestan
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="religion" value="Kristen Katolik"
                                id="Kristen Katolik" {{ old('religion') == 'Kristen Katolik' ? 'checked' : '' }}>
                            <label class="form-check-label" for="Kristen Katolik">
                                Kristen Katolik
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="religion" value="Hindu"
                                id="Hindu" {{ old('religion') == 'Hindu' ? 'checked' : '' }}>
                            <label class="form-check-label" for="Hindu">
                                Hindu
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="religion" value="Buddha"
                                id="Buddha" {{ old('religion') == 'Buddha' ? 'checked' : '' }}>
                            <label class="form-check-label" for="Buddha">
                                Buddha
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="religion" value="Konghucu"
                                id="Konghucu" {{ old('religion') == 'Konghucu' ? 'checked' : '' }}>
                            <label class="form-check-label" for="Konghucu">
                                Konghucu
                            </label>
                        </div>
                        @if ($errors->has('religion'))
                            <div class="error">{{ $errors->first('religion') }}</div>
                        @endif
                    </div>


                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Informasi Kepegawaian</h6>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label class="label d-block" for="status">Status Karyawan</label>
                        <input type="checkbox" checked class="d-block" id="toggleStatus" data-toggle="toggle"
                            data-on="Aktif" data-off="Nonaktif" data-onstyle="success" data-offstyle="danger"
                            data-size="sm">
                        <input type="hidden" name="status" id="status" value="1">


                    </div>
                    <div class="form-group">
                        <label class="label" for="nip">NIP</label>
                        <input type="text" class="form-control" name="nip"
                            placeholder="Masukkan Nomor Induk Pegawai (NIP)" value="{{ old('nip') }}">
                        @if ($errors->has('nip'))
                            <div class="error">{{ $errors->first('nip') }}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="label" for="position">Posisi</label>
                        <select name="position_id" class="form-control">
                            <option value="">--Pilih Posisi--</option>
                            @foreach ($position as $item)
                                <option value="{{ $item->id }}"
                                    {{ old('position_id') == $item->id ? 'selected' : '' }}> {{ $item->name }} </option>
                            @endforeach
                        </select>
                        @if ($errors->has('position_id'))
                            <div class="error">{{ $errors->first('position_id') }}</div>
                        @endif

                    </div>
                    <div class="form-group">
                        <label class="label" for="department">Departemen</label>
                        <input type="text" class="form-control" name="department"
                            placeholder="Masukkan nama departemen" value="{{ old('department') }}">
                        @if ($errors->has('department'))
                            <div class="error">{{ $errors->first('department') }}</div>
                        @endif
                    </div>

                </div>
            </div>
            <div class="card mt-3">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Unggah Kartu Tanda Penduduk (KTP)</h6>
                </div>
                <div class="card-body">
                    <div class="custom-file">
                        <input id="logo" type="file" name="ktp" accept=".jpg, .png, .jpeg"
                            class="custom-file-input">
                        <label for="logo" class="custom-file-label text-truncate">Pilih berkas...</label>
                        @if ($errors->has('ktp'))
                            <div class="error">{{ $errors->first('ktp') }}</div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary ml-3 mt-3 px-5"><i class="fa fa-solid fa-user-plus"></i> Tambah
            Karyawan</button>
    </form>
@endsection
@push('js')
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>


    <script>
        $(document).ready(function() {
            changeBirthDate();
            $('.date_of_birth').change(function() {
                changeBirthDate()
            });
            $('.custom-file-input').on('change', function() {
                let fileName = $(this).val().split('\\').pop();
                $(this).next('.custom-file-label').addClass("selected").html(fileName);
            });
            $('#toggleStatus').change(function() {
                if ($('#toggleStatus').is(':checked')) {
                    $('#status').val(1);
                } else {
                    $('#status').val(0);
                }
            });
        });

        function changeBirthDate() {
            var day = $("#select_day option:selected").val();
            var month = $("#select_month option:selected").val();
            var year = $("#select_year option:selected").val();
            if (day < 10) {
                day = '0' + day;
            }
            $('#birth_date').val(year + '-' + month + '-' + day);
        }
    </script>
@endpush

resources/views/employee/index.blade.php
@extends('layout.app')

@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
@endsection
@section('breadcrumb')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Karyawan</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Karyawan</li>
        </ol>
    </div>
@endsection
@section('content')
    <a href=" {{ route('employee.create') }} " class="btn btn-primary mb-4"> <i class="fa fa-solid fa-user-plus"></i> Tambah
        Karyawan</a>
    <div class="card sm mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Data Karyawan</h6>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive p-3">
                <table class="table table-hover table-sm w-100" id="dataTable">
                    <thead class="thead-light text-nowrap">
                        <tr>
                            <th>No.</th>
                            <th>Nama Karyawan</th>
                            <th>NIP</th>
                            <th>Jabatan</th>
                            <th>Departemen</th>
                            <th>Status</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No.</th>
                            <th>Nama Karyawan</th>
                            <th>NIP</th>
                            <th>Jabatan</th>
                            <th>Departemen</th>
                            <th>Status</th>
                            <th>Opsi</th>

                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src=" {{ asset('vendor/sweetalert/sweetalert.all.js') }} "></script>

    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('employee.index') }}",
                columns: [{
                        data: 'DT_RowIndex',
                        orderable: false,
                        searchable: false,
                        className: "text-center"
                    },
                    {
                        data: 'fullname'
                    },
                    {
                        data: 'nip'
                    },
                    {
                        data: 'position'
                    },
                    {
                        data: 'department'
                    },
                    {
                        data: 'status',
                        searchable: false,
                        orderable: false,
                    },
                    {
                        data: 'action',
                        orderable: false,
                        searchable: false
                    }
                ],
                order: [
                    [1, 'asc']
                ],
                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.13.2/i18n/id.json',
                },
                initComplete: function() {
                    this.api()
                        .columns([3, 4])
                        .every(function() {
                            var column = this;
                            var select = $('<select><option value=""></option></select>')
                                .appendTo($(column.footer()).empty())
                                .on('change', function() {
                                    var val = $.fn.dataTable.util.escapeRegex($(this).val());

                                    column.search(val ? '^' + val + '$' : '', true, false)
                                        .draw();
                                });

                            column
                                .data()
                                .unique()
                                .sort()
                                .each(function(d, j) {
                                    select.append('<option value="' + d + '">' + d +
                                        '</option>');
                                });
                        });
                },
            });
        });
    </script>
@endpush

resources/views/employee/show.blade.php
@extends('layout.app')

@section('css')
@endsection
@section('breadcrumb')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Detail Karyawan </h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
            <li class="breadcrumb-item"> <a href="{{ route('employee.index') }}">Karyawan</a> </li>
            <li class="breadcrumb-item active" aria-current="page"> Detail Karyawan </li>
        </ol>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12 mb-4">
            <a href=" {{ route('employee.edit', $employee->ID_emp) }} " class="btn btn-info mr-2"><i
                    class='fas fa-user-edit mr-2'></i>Edit Data</a>
            <form action="{{ route('employee.destroy', $employee->ID_emp) }}" method="post" class="d-inline">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <button type="submit" class="btn btn-danger mr-2"><i class='fas fa-user-times mr-2'></i>Hapus Data</button>
            </form>
        </div>
        <div class="col-md-6">
            <div class="card sm mb-4">
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between m-auto bg-blue rounded-0 px-5">
                    <h6 class="m-0 font-weight-bold text-primary">Identitas Karyawan </h6>
                </div>
                <div class="card-body">
                    <table class="table table-borderless">
                        <tr>
                            <td>Nama Lengkap</td>
                            <td>:</td>
                            <td> {{ $employee->fullname }} </td>
                        </tr>
                        <tr>
                            <td>Tanggal Lahir</td>
                            <td>:</td>
                            <td> {{ $employee->birth_date }} </td>
                        </tr>
                        <tr>
                            <td>Nomor Telepon</td>
                            <td>:</td>
                            <td> {{ $employee->phone_number }} </td>
                        </tr>
                        <tr>
                            <td>Alamat</td>
                            <td>:</td>
                            <td> {{ $employee->address }} </td>
                        </tr>
                        <tr>
                            <td>Agama</td>
                            <td>:</td>
                            <td> {{ $employee->religion }} </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="card sm">
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between m-auto bg-blue rounded-0 px-5">
                    <h6 class="m-0 font-weight-bold text-primary">KTP </h6>
                </div>
                <div class="card-body text-center">
                    <img src=" {{ asset('storage/ktp/' . $employee->ktp) }} " class="img-fluid" alt=""
                        srcset="">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card sm">
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between m-auto bg-blue rounded-0 px-5">
                    <h6 class="m-0 font-weight-bold text-primary">Informasi Kepegawaian </h6>
                </div>
                <div class="card-body">
                    <table class="table table-borderless">
                        <tr>
                            <td>NIP</td>
                            <td>:</td>
                            <td> {{ $employee->nip }} </td>
                        </tr>
                        <tr>
                            <td>Status Karyawan</td>
                            <td>:</td>
                            <td>
                                @if ($employee->status == '1')
                                    <h5><span class="badge badge-pill badge-success">Aktif</span></h5>
                                @else
                                    <h5><span class="badge badge-pill badge-danger">Nonaktif</span></h5>
                                @endif
                            </td>
                        </tr>

                        <tr>
                            <td>Posisi</td>
                            <td>:</td>
                            <td> {{ $employee->position }} </td>
                        </tr>
                        <tr>
                            <td>Departemen</td>
                            <td>:</td>
                            <td> {{ $employee->department }} </td>
                        </tr>

                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection